### ISSUE TITLE
OOP Content Additions

### ISSUE THREAD

**Issue by MissMeg** [MissMeg/oop-for-beginners#3]
- [ ] #4 Additional practice files focusing on each section area for further examples.
- [x] #5 [Inheritance](https://github.com/MissMeg/oop-for-beginners/tree/master/Beginner_OOP#inheritance) (beginner): Explain what inheritance is with a simple example
- [x] #6 [Encapsulation](https://github.com/MissMeg/oop-for-beginners/tree/master/Beginner_OOP#encapsulation) (beginner): Explain what encapsulation is with a simple example
- [x] #7 [Polymorphism](https://github.com/MissMeg/oop-for-beginners/tree/master/Beginner_OOP#polymorphism) (beginner): Explain what polymorphism is with a simple example
- [x] #8 Intermediate OOP: Create an outline for intermediate OOP

If you are interested in taking on one of the above issues, please go to its page and comment that you will be taking it on.
